// ANALYTICS
const API_AVRO_FORMAT = 'avro';
const API_CSV_FORMAT = 'csv';
const API_JSON_FORMAT = 'json';
const API_EXTRACTION_FILE_FORMATS = [
  API_AVRO_FORMAT,
  API_JSON_FORMAT,
  API_CSV_FORMAT,
];

const API_DAY_PERIOD = 'DAY';
const API_MONTH_PERIOD = 'MONTH';
const API_YEAR_PERIOD = 'YEAR';
const API_DATETIME_PERIODS = [
  API_DAY_PERIOD,
  API_MONTH_PERIOD,
  API_YEAR_PERIOD,
];

const API_PUBLICATION_DATETIME_FIELD = 'publication_datetime';
const API_MODIFICATION_DATETIME_FIELD = 'modification_datetime';
const API_INGESTION_DATETIME_FIELD = 'ingestion_datetime';
const API_DATETIME_FIELDS = [
  API_PUBLICATION_DATETIME_FIELD,
  API_MODIFICATION_DATETIME_FIELD,
  API_INGESTION_DATETIME_FIELD,
];

module.exports = {
  API_AVRO_FORMAT,
  API_CSV_FORMAT,
  API_JSON_FORMAT,
  API_DAY_PERIOD,
  API_MONTH_PERIOD,
  API_YEAR_PERIOD,
  API_PUBLICATION_DATETIME_FIELD,
  API_MODIFICATION_DATETIME_FIELD,
  API_INGESTION_DATETIME_FIELD,
  API_EXTRACTION_FILE_FORMATS,
  API_DATETIME_PERIODS,
  API_DATETIME_FIELDS,
};
