// API STATES
const API_JOB_CREATED_STATE = 'JOB_CREATED';
const API_JOB_QUEUED_STATE = 'JOB_QUEUED';
const API_JOB_PENDING_STATE = 'JOB_STATE_PENDING';
const API_JOB_VALIDATING_STATE = 'JOB_VALIDATING';
const API_JOB_STATE_VALIDATING = 'JOB_STATE_VALIDATING';
const API_JOB_RUNNING_STATE = 'JOB_STATE_RUNNING';
const API_JOB_DONE_STATE = 'JOB_STATE_DONE';
const API_JOB_FAILED_STATE = 'JOB_STATE_FAILED';
const API_JOB_CANCELLED_STATE = 'JOB_STATE_CANCELLED';

const API_JOB_EXPECTED_STATES = [
  API_JOB_CREATED_STATE,
  API_JOB_QUEUED_STATE,
  API_JOB_PENDING_STATE,
  API_JOB_VALIDATING_STATE,
  API_JOB_STATE_VALIDATING,
  API_JOB_RUNNING_STATE,
  API_JOB_DONE_STATE,
  API_JOB_FAILED_STATE,
  API_JOB_CANCELLED_STATE,
];

const API_JOB_ACTIVE_WAIT_SPACING = 10;

module.exports = {
  API_JOB_EXPECTED_STATES,
  API_JOB_ACTIVE_WAIT_SPACING,
  API_JOB_CREATED_STATE,
  API_JOB_QUEUED_STATE,
  API_JOB_PENDING_STATE,
  API_JOB_VALIDATING_STATE,
  API_JOB_STATE_VALIDATING,
  API_JOB_RUNNING_STATE,
  API_JOB_DONE_STATE,
  API_JOB_FAILED_STATE,
  API_JOB_CANCELLED_STATE,
};
