// Snapshots
const API_SNAPSHOTS_BASEPATH = '/alpha/extractions/documents';
const API_EXPLAIN_SUFFIX = '/_explain';
const API_ANALYTICS_BASEPATH = '/alpha/analytics';
const API_EXTRACTIONS_BASEPATH = '/alpha/extractions';
const API_EXTRACTIONS_SAMPLES_SUFFIX = '/samples';
const API_DEFAULT_EXTRACTION_TYPE = 'documents';
const API_SAMPLES_EXTRACTION_TYPE = 'samples';

const API_SNAPSHOTS_TAXONOMY_BASEPATH = '/alpha/taxonomies';
const API_SNAPSHOTS_COMPANIES_BASEPATH = '/alpha/companies';
const API_SNAPSHOTS_COMPANY_IDENTIFIERS_BASEPATH =
  '/alpha/companies/identifiers';
const API_SNAPSHOTS_COMPANIES_PIT = '/pit';
const CUSIP_COMPANY_IDENTIFIER = 'cusip';
const ISIN_COMPANY_IDENTIFIER = 'isin';
const SEDOL_COMPANY_IDENTIFIER = 'sedol';
const TICKER_COMPANY_IDENTIFIER = 'ticker';
const API_COMPANIES_IDENTIFIER_TYPE = [
  CUSIP_COMPANY_IDENTIFIER,
  ISIN_COMPANY_IDENTIFIER,
  SEDOL_COMPANY_IDENTIFIER,
  TICKER_COMPANY_IDENTIFIER,
];

module.exports = {
  API_SNAPSHOTS_BASEPATH,
  API_EXPLAIN_SUFFIX,
  API_ANALYTICS_BASEPATH,
  API_EXTRACTIONS_BASEPATH,
  API_SNAPSHOTS_TAXONOMY_BASEPATH,
  API_SNAPSHOTS_COMPANIES_BASEPATH,
  API_SNAPSHOTS_COMPANY_IDENTIFIERS_BASEPATH,
  API_EXTRACTIONS_SAMPLES_SUFFIX,
  API_DEFAULT_EXTRACTION_TYPE,
  API_SAMPLES_EXTRACTION_TYPE,
  API_SNAPSHOTS_COMPANIES_PIT,
  API_COMPANIES_IDENTIFIER_TYPE,
  CUSIP_COMPANY_IDENTIFIER,
  ISIN_COMPANY_IDENTIFIER,
  SEDOL_COMPANY_IDENTIFIER,
  TICKER_COMPANY_IDENTIFIER,
};
