// Snapshots
const API_SNAPSHOTS_BASEPATH = '/alpha/extractions/documents';
const API_EXPLAIN_SUFFIX = '/_explain';
const API_ANALYTICS_BASEPATH = '/alpha/analytics';
const API_EXTRACTIONS_BASEPATH = '/alpha/extractions';

const API_SNAPSHOTS_TAXONOMY_BASEPATH = '/alpha/taxonomies';
const API_SNAPSHOTS_COMPANIES_BASEPATH = '/alpha/companies';
const API_SNAPSHOTS_COMPANY_IDENTIFIERS_BASEPATH = '/alpha/companies/identifiers';

module.exports = {
  API_SNAPSHOTS_BASEPATH,
  API_EXPLAIN_SUFFIX,
  API_ANALYTICS_BASEPATH,
  API_EXTRACTIONS_BASEPATH,
  API_SNAPSHOTS_TAXONOMY_BASEPATH,
  API_SNAPSHOTS_COMPANIES_BASEPATH,
  API_SNAPSHOTS_COMPANY_IDENTIFIERS_BASEPATH
};
