// Streams
const API_STREAMS_BASEPATH = '/alpha/streams';
// eslint-disable-next-line
const API_ACCOUNT_STREAM_CREDENTIALS_BASEPATH = '/accounts/streaming-credentials';
const DOC_COUNT_EXCEEDED = 'DOC_COUNT_EXCEEDED';
const CHECK_EXCEEDED_WAIT_SPACING = 3000;
const PUBSUB_MESSAGES_WAIT_SPACING = 10;

module.exports = {
  API_STREAMS_BASEPATH,
  API_ACCOUNT_STREAM_CREDENTIALS_BASEPATH,
  DOC_COUNT_EXCEEDED,
  CHECK_EXCEEDED_WAIT_SPACING,
  PUBSUB_MESSAGES_WAIT_SPACING,
};
