// Streams
const API_STREAMS_BASEPATH = '/alpha/streams';
// eslint-disable-next-line
const DOC_COUNT_EXCEEDED = 'DOC_COUNT_EXCEEDED';
const CHECK_EXCEEDED_WAIT_SPACING = 300;
const PUBSUB_MESSAGES_WAIT_SPACING = 10;

module.exports = {
  API_STREAMS_BASEPATH,
  DOC_COUNT_EXCEEDED,
  CHECK_EXCEEDED_WAIT_SPACING,
  PUBSUB_MESSAGES_WAIT_SPACING,
};
